goadus/urls.py
# SPDX-PackageName: goadus-website
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/finnix/goadus-website
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

"""goadus URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="goadus/login.html"),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="goadus/logout.html"),
        name="logout",
    ),
    path("admin/", admin.site.urls),
    path("api/upload/", views.api_upload, name="api-upload"),
    path("image/<slug>/", views.ImageView.as_view(), name="image"),
    path("imageset/<slug>/", views.ImageSetView.as_view(), name="imageset"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.views.static import serve

    def serve_subdir_fn(request, path, document_root, **kwargs):
        path = "{}/{}/{}".format(path[0:1], path[1:2], path)
        return serve(request, path, document_root, **kwargs)

    urlpatterns += static(settings.MEDIA_URL, view=serve_subdir_fn, document_root=settings.MEDIA_ROOT)

goadus/models.py
# SPDX-PackageName: goadus-website
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/finnix/goadus-website
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

import os
import uuid

from django.conf import settings
from django.core.files import storage
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from .utils import werder_api_key, werder_name


class IGoadStorage(storage.FileSystemStorage):
    def url(self, name):
        return storage.FileSystemStorage.url(self, os.path.split(name)[-1])


class ImageSet(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False, null=False)
    slug = models.SlugField(default=werder_name, unique=True, blank=False, null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False)
    date_added = models.DateTimeField(default=timezone.now, blank=False, null=False)
    date_expires = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy("imageset", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug


class Image(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False, null=False)
    slug = models.SlugField(default=werder_name, unique=True, blank=False, null=False)
    original_filename = models.CharField(max_length=200, blank=False, null=False)
    content_type = models.CharField(max_length=200, blank=True, null=True)
    image_set = models.ForeignKey(ImageSet, on_delete=models.CASCADE, blank=False, null=False)

    def get_absolute_url(self):
        return reverse_lazy("image", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug


class ImageFile(models.Model):
    TYPES = (
        ("uploaded", "Unsanitized original image"),
        ("original", "Original image"),
        ("medium", "Resized image"),
        ("thumbnail", "Thumbnail image"),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False, null=False)
    file = models.ImageField(max_length=200, storage=IGoadStorage(), blank=False, null=False)
    type = models.CharField(max_length=200, choices=TYPES, blank=False, null=False)
    image = models.ForeignKey(Image, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return os.path.split(self.file.name)[-1]


class ApiKey(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, blank=False, null=False)
    slug = models.SlugField(default=werder_api_key, unique=True, blank=False, null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False)
    date_added = models.DateTimeField(default=timezone.now, blank=False, null=False)
    date_expires = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.slug

goadus/templates/goadus/base.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ site.name }}</title>
  <link rel="stylesheet" href="{% static 'goadus/darkly.min.css' %}">
  <link rel="stylesheet" href="{% static 'goadus/style.css' %}">
</head>
<body>
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>

goadus/templates/goadus/image.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% extends "./base.html" %}

{% block content %}
<h1>{{ object.original_filename }}</h1>
<table class="table">
<tr><th>Filename</th><th>Image Size</th><th>Bytes</th><th>Uploaded</th></tr>
{% for image_file in object.imagefile_set.all %}
{% if image_file.type != 'uploaded' %}
<tr>
<td><a rel="nofollow" href="{{ image_file.file.url }}">{{ image_file }}</a></td>
<td>{{ image_file.file.width }}×{{ image_file.file.height }} ({{ image_file.type }})</td>
<td>{{ image_file.file.size }}</td>
<td>{{ image_file.date_added }}</td>
</tr>
{% endif %}
{% endfor %}
</table>
<p>Uploaded {{ object.image_set.date_added }} by {{ object.image_set.user }}.</p>
{% if object.image_set.date_expires %}
<p>Image will be deleted in approximately {{ object.image_set.date_expires|timeuntil }}.</p>
{% endif %}
{% endblock %}

goadus/templates/goadus/imageset.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% extends "./base.html" %}

{% block content %}
{% for image in object.image_set.all %}
<h1><a href="{% url 'image' image %}">{{ image.original_filename }}</a></h1>
<table class="table">
<tr><th>Filename</th><th>Image Size</th><th>Bytes</th></tr>
{% for image_file in image.imagefile_set.all %}
{% if image_file.type != 'uploaded' %}
<tr>
<td><a rel="nofollow" href="{{ image_file.file.url }}">{{ image_file }}</a></td>
<td>{{ image_file.file.width }}×{{ image_file.file.height }} ({{ image_file.type }})</td>
<td>{{ image_file.file.size }}</td>
</tr>
{% endif %}
{% endfor %}
</table>
<hr/>
{% endfor %}
<p>Uploaded {{ object.date_added }} by {{ object.user }}.</p>
{% if object.date_expires %}
<p>Image set will be deleted in approximately {{ object.date_expires|timeuntil }}.</p>
{% endif %}
{% endblock %}

goadus/templates/goadus/index.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>goad.us</title>
  <link rel="stylesheet" href="{% static 'goadus/darkly.min.css' %}">
  <link rel="stylesheet" href="{% static 'goadus/style.css' %}">
</head>

<!-- https://commons.wikimedia.org/wiki/File:Grey_squirrel_(Sciurus_carolinensis)_02.jpg -->
<body style="margin: 0; padding: 0;">
<div class="container" id="bigsquirrel" style="height:100vh; width: 100vw; max-height: 100vh; max-width: 100vw; padding: 0; text-align: center;">
<img src="{% static 'goadus/squirrel.jpg' %}" style="max-width: 100vw; max-height: 100vh;">
</div>
<script src="{% static 'goadus/jquery.js' %}"></script>
<script src="{% static 'goadus/jquery.zoom.js' %}"></script>
<script>
  if ($ && $.fn.zoom) {
    $('#bigsquirrel').zoom({});
  }
</script>
</body>
</html>

goadus/templates/goadus/login.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% extends "./base.html" %}

{% block content %}

<h1>Login</h1>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

goadus/templates/goadus/logout.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% extends "./base.html" %}

{% block content %}
<h1>Logout</h1>
<p>You have been logged out.</p>
<p><a href="{% url 'login' %}">Login</a></p>
{% endblock %}

goadus/templates/goadus/upload.html
{#- SPDX-PackageName: goadus-website #}
{#- SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-PackageDownloadLocation: https://github.com/rfinnie/goadus-website #}
{#- SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org> #}
{#- SPDX-License-Identifier: MPL-2.0 #}
{% extends "./base.html" %}

{% block content %}
<h1>Upload</h1>

{% load crispy_forms_tags %}
{% crispy form %}

<h2>Recent Uploads</h2>
<table class="table">
<tr><th>Image Set</th><th>Uploaded</th></tr>
{% for imageset in request.user.imageset_set.all|dictsortreversed:"date_added"|slice:":10" %}
<tr>
<td><a rel="nofollow" href="{% url 'imageset' imageset %}">{{ imageset }}</a></td>
<td>{{ imageset.date_added }}</td>
</tr>
{% endfor %}
</table>

<p><a href="{% url 'logout' %}">Logout</a></p>
{% endblock %}